amazonProperties:
    endpointUrl: https://s3.us-east-2.amazonaws.com
    accessKey: AKIAIHK6MI3PHVMRYDBQ
    secretKey: 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
    bucketName: photois-avatars-bucket